### ISSUE TITLE
Can't download charts

### ISSUE THREAD

**Issue by AndriiKrasnopieiev** [SafetyGraphics/safetyGraphics#656] opened 2021-12-22 10:47 UTC
Hi, 

When I press 'Download RTF' or 'html report' the error occurs - "Failed - Server problem". 
So I can't download any results.

How can it be resolved? 
Will appreciate any help.

Thanks in advance!

**Comment by jwildfire** [comment] 2022-01-04 17:14
Hi @AndriiKrasnopieiev - Sorry to hear you're having issues. I have seen similar issues sporadically, but nothing consistent. 

I've got a few questions that might help us de-bug. Are you running the app locally using RStudio?  Is this happening for all charts? Could your provide the output of sessionInfo() and any errors that come up in the R console?

**Comment by AndriiKrasnopieiev** [comment] 2022-01-20 09:13
Hi @jwildfire ,

Thanks for your response.

Yes, I have this error even with your test data/charts.

Warning: Error in %>%: could not find function "%>%"
  [No stack trace available]
![image](https://user-images.githubusercontent.com/96524751/150308750-1e9721d1-a6e5-43b6-840e-6a2f4eb6c535.png)

**Comment by jwildfire** [comment] 2022-02-17 16:18
Thanks for posting the log @AndriiKrasnopieiev! I think this is related to this issue in [safetyCharts](https://github.com/SafetyGraphics/safetyCharts/issues/79) that has been fixed in the development version of the package on GitHub. Can you try running this code removing the broken chart and let me know if the issue is resolved: 

```
library(safetyGraphics)
charts <- makeChartConfig()
charts$demogRTF <- NULL
safetyGraphicsApp(charts=charts)
```

You can also load the development version of safetyCharts from GitHub (`devtools::install_github('safetygraphics\safetyCharts', ref='dev')` and then run the app with no modification.  I'll try to release the new version of safetyCharts and push to CRAN ASAP, to clear this up.

**Closed** 2022-03-03 14:08 UTC
Labels: bug
