### ISSUE TITLE
Calling chart modules dynamically produces bug in validation

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#222] opened 2019-03-27 16:48 UTC
Current code (loop + callModule + reactives) is not amenable to sending the chart-specific validation.

#217 will be a better approach and hopefully will solve this.

**Comment by jwildfire** [comment] 2019-04-18 16:52
Duplicate of #230 which won't be using the same loop framework mentioned above.

**Closed by jwildfire** 2019-04-18 16:52 UTC
Labels: bug
