### ISSUE TITLE
Names of chart configuration files must match htmlwidgets .yaml files (?).

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyGraphics#503] opened 2021-03-19 19:33 UTC
I'm just trying to think through how `safetyGraphics` works below.

Potentially not an issue, but renaming a set of custom chart configuration files seems to have disassociated the configuration files from the chart code.  I assume the name of the configuration files is also their ID to connect a configuration with the charting code.  Reverting the naming scheme fixed the issue but I'm wondering why the name of the configuration file is needed.  The `workflow` property captures the `htmlwidgets` dependency...

To define a chart we need:

- data (passed to the app on initialization)
- chart code (stored either locally relative to the location of the app or in the `safetyCharts` library)
- settings (passed to the app on initialization or modified in a `workflow` function)
- label (captured in the configuration file)
- chart type (`htmlwidget`, `plot`, `module`, `html`, `table`, etc.) - I think this is where I'm confused - if chart type is set to `htmlwidget` where does `safetyGraphics` look for the .js code, in `safetyGraphics`, in `safetyCharts`, in the chart configuration file location?  **`htmlwidgets` lib is sourced from `safetyCharts`**

`htmlwidgets` convention is that the name of the YAML matches the name of the .js file name (or global variable name?).  What if we wanted more than one instance of an `htmlwidget`?  I feel like the chart YAMLs should be customizable.

**Comment by jwildfire** [comment] 2021-04-12 16:16
Hmm. Not sure I have the brainpower to deal with this on my first day back, but will assign myself to think through it and reply soon.

**Comment by jwildfire** [comment] 2021-04-19 14:38
Ok, looking at this again. I can confirm that, yes, the `name` of the chart is just set as the name of the yaml config file (see [here](https://github.com/SafetyGraphics/safetyGraphics/blob/63bee7e2257784570327d18352bd2c462dc4158e/R/makeChartConfig.R#L69)). Maybe not ideal ... I guess we could allow a name parameter that overrides the file name when given? 

Some (most?) of your other questions are addressed in [this vignette](https://github.com/SafetyGraphics/safetyGraphics/wiki/Chart-Configuration-Vignette-(v2)). It's still a bit of a mess, but should cover most of the basics. Edits VERY welcome! A few other little things below. 

> I think this is where I'm confused - if chart type is set to htmlwidget where does safetyGraphics look for the .js code

You specify the `package` in the yaml config, and it looks in the `inst` folder there

> What if we wanted more than one instance of an htmlwidget?

Yeah, this is a good question. Don't think it's doable now (well, I guess you can always just run 2 instance of the app, but not ideal.) The intent was for the widget name to come from chart$workflow$widget, but it's currently just pulling the name (see #443). I think once that is fixed, you could just have 2 yaml files pointing to the same widget, but not 100% sure it will work. 

OK, Going to close this since we've already got #443, but feel free to reply and re-open if you think there are other updates needed.

**Closed by jwildfire** 2021-04-19 14:38 UTC
